### ISSUE TITLE
Support constructor name transformations

### ISSUE THREAD

**Issue by travisbrown** [circe/circe-derivation#110]
We support `transformMemberNames`, for changing the names of case class members in their JSON representation, but don't yet support `transformConstructorNames` for ADTs. The behavior should be the same as that provided by [circe-generic-extras](https://github.com/circe/circe-generic-extras).

**Comment by danxmoran** [comment]
Hey @travisbrown I saw in your release notes for 0.12.0-M7 that this is the main blocker for an 0.12.0 release. I'd be happy to try contributing it, if you're still looking for volunteers!

**Comment by travisbrown** [comment]
Yes, for sure, that'd be great! Let us know if you have questions.

**Comment by danxmoran** [comment]
I've gotten to the point where I think I'm ready to test the new functionality, but I'm stuck trying to un-break the existing tests. The compiler keeps hitting an assertion error in the `delambdafy` phase when trying to derive the decoder for a top-level `trait` in an ADT. The assertion is checking that some function has a `STATIC` flag set (I haven't figured out which function is missing the flag, but I'd guess it's the name-transformation lambda).

I'll keep digging into what might be wrong, but if you get any time to take a look I'd appreciate the help. I've pushed my WIP to [this branch](https://github.com/danxmoran/circe-derivation/tree/danxmoran/fix-110-ctor-name-transforms).

**Comment by travisbrown** [comment]
Done in #114 and #186.
