### ISSUE TITLE
Upgrade to circe 0.9.0

### ISSUE THREAD

**Issue by Tvaroh** [circe/circe-derivation#17]

**Comment by ranchoiver** [comment]
+1

**Comment by Tvaroh** [comment]
@travisbrown hey Travis, are you going to publish Circe 0.9 compatible version? Are there any blocks on this?

**Comment by travisbrown** [comment]
Available as 0.9.0-M1 [since early January](https://github.com/circe/circe-derivation/releases/tag/v0.9.0-M1).
