### ISSUE TITLE
Derivation fails if there's an .apply() method with different field names

### ISSUE THREAD

**Issue by kaishh** [circe/circe-derivation#21]
Minimal example:

```scala
import io.circe._
import io.circe.derivation._

case class Abc(x: String)

object Abc {
  implicit val dec: Decoder[Abc] = deriveDecoder[Abc]
  implicit val enc: ObjectEncoder[Abc] = deriveEncoder[Abc]

  def apply(otherfield: Int): Abc = new Abc(otherfield.toString)
}
```
```
Error:(7, 50) No method otherfield in A$A111.this.Abc (this is probably because a constructor parameter isn't a val)
  implicit val dec: Decoder[Abc] = deriveDecoder[Abc]
                                                ^
Error:(8, 56) No method otherfield in A$A111.this.Abc (this is probably because a constructor parameter isn't a val)
  implicit val enc: ObjectEncoder[Abc] = deriveEncoder[Abc]
                                                      ^
```
But If it's `def apply(x: Int): Abc = new Abc(x)` then it works

**Comment by travisbrown** [comment]
Hmm, good catch, thanks. I think we probably want to ensure that both the names and types match up, have a better error message for this case, and document the fact that if the user has custom constructor logic it'll get applied on decoding.

In the meantime I don't think the current error is _so_ terrible…

**Comment by kaishh** [comment]
@travisbrown 
>  I think we probably want to ensure that both the names and types match up, have a better error message for this case, and document the fact that if the user has custom constructor logic it'll get applied on decoding.

Err, why do we need to touch .apply() or apply it to decoding? AFAIK `tysym.decl(c.universe.termNames.CONSTRUCTOR)` gives the real constructor we can use to generate instance.

**Comment by travisbrown** [comment]
@kaishh Right now it's primarily for cases like Scrooge, where there's not a "real" public constructor, but it can also be the case for Scala's case classes:

```scala
scala> case class Foo private(x: Int)
defined class Foo

scala> Foo(1)
res0: Foo = Foo(1)

scala> new Foo(1)
<console>:14: error: constructor Foo in class Foo cannot be accessed in object $iw
       new Foo(1)
       ^
```

I think maybe we should reverse the order the two approaches are tried, though, so that we look for a valid constructor first, and then fall back to `apply`.

**Comment by kaishh** [comment]
@travisbrown 
That would be good, and more closely match how semiauto works. Right now I'm trying to integrate circe derivation into [izumi-IDL](https://github.com/pshirshov/izumi-r2) to speedup model compilation, but this issue is a blocker, since we're using .apply() to generate non-primary constructors.
